version: '3.8'

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./frontend/build:/var/www/html
      - ./frontend/nginx.conf:/etc/nginx/sites-available/default
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://db/geeltech
      JWT_SECRET: mom&dad
      SMTP_SERVER: gmail
      SMTP_USER: ahmaat19@gmail.com
      SMTP_PORT: 587
      SMTP_KEY: bjafgcqqgidywuom
    restart: unless-stopped
  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - geeltech:/data/db
    restart: unless-stopped

volumes:
  geeltech:
