version: '3.8'

services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  api:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://db/geeltech
      JWT_SECRET: mom&dad
      SMTP_SERVER: gmail
      SMTP_USER: ahmaat19@gmail.com
      SMTP_PORT: 587
      SMTP_KEY: bjafgcqqgidywuom
    volumes:
      - ./backend:/app
  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - geeltech:/data/db

volumes:
  geeltech:
